version: '3.8'
services:
  flask_api:
    container_name: flask_api
    restart: always
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
    networks:
      - db_network

networks:
  db_network:
    driver: bridge